TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += fc_maps.proto
DATA += fc_merlin.proto

#=======================================
include $(TOP)/configure/RULES
