TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += devfc.proto

#=======================================
include $(TOP)/configure/RULES
